#!/usr/bin/env python3
"""Inject Vane's minimal modgui into a built Vane.lv2 bundle.

JUCE regenerates the LV2 bundle on every build with no modgui, so run this
afterwards (idempotent) to:
  1. copy modgui/ assets into the bundle,
  2. read the real lv2:index for each control port from the bundle's *.ttl,
  3. append a modgui:gui block (with those ports) to manifest.ttl.

Usage:
    python3 Tools/modgui/apply.py <path/to/Vane.lv2>

Then install as usual:
    sudo cp -r <path/to/Vane.lv2> /var/modep/lv2/
    sudo systemctl restart modep-mod-ui modep-mod-host
"""
import os, re, shutil, sys

# Port symbol -> label shown under the knob, in display order.
CONTROLS = [
    ("filterCutoff", "Cutoff"),
    ("glideTime",    "Glide"),
    ("monoMode",     "Mono"),
    ("unisonMode",   "Voicing"),
]
DEFAULT_URI = "https://enkerli.com/plugins/Vane"
BEGIN = "# >>> vane modgui (generated by Tools/modgui/apply.py)"
END   = "# <<< vane modgui"


def read_all_ttl(bundle):
    text = ""
    for fn in os.listdir(bundle):
        if fn.endswith(".ttl"):
            with open(os.path.join(bundle, fn), encoding="utf-8") as f:
                text += f.read() + "\n"
    return text


def find_uri(ttl):
    m = re.search(r"<(https?://[^>]+)>\s*\n?\s*a\s+lv2:Plugin", ttl)
    return m.group(1) if m else DEFAULT_URI


def symbol_indices(ttl):
    """Map every control-port symbol to its lv2:index.  Each symbol takes the
    most recent lv2:index seen before it (nested scalePoint blank nodes carry
    neither predicate, so they don't interfere).  Order-independent re: which
    appears first is not assumed beyond 'index precedes symbol in JUCE output'."""
    out, cur = {}, None
    for line in ttl.splitlines():
        mi = re.search(r"lv2:index\s+(\d+)", line)
        if mi:
            cur = int(mi.group(1))
        ms = re.search(r'lv2:symbol\s+"([^"]+)"', line)
        if ms and cur is not None:
            out[ms.group(1)] = cur   # do NOT reset cur; see docstring
    return out


def build_block(uri, idx):
    ports = []
    for sym, name in CONTROLS:
        if sym not in idx:
            print(f"  WARN: port symbol {sym!r} not found in bundle TTL — skipping")
            continue
        ports.append(
            "[\n"
            f"            lv2:index {idx[sym]} ;\n"
            f'            lv2:symbol "{sym}" ;\n'
            f'            lv2:name "{name}" ;\n'
            "        ]"
        )
    # One modgui:port predicate; blank nodes are comma-separated objects.
    ports_ttl = "        modgui:port " + " , ".join(ports)
    return (
        f"\n{BEGIN}\n"
        "@prefix modgui: <http://moddevices.com/ns/modgui#> .\n\n"
        f"<{uri}>\n"
        "    modgui:gui [\n"
        "        modgui:resourcesDirectory <modgui> ;\n"
        "        modgui:iconTemplate <modgui/icon.html> ;\n"
        "        modgui:stylesheet <modgui/style.css> ;\n"
        "        modgui:screenshot <modgui/screenshot.png> ;\n"
        "        modgui:thumbnail <modgui/thumbnail.png> ;\n"
        '        modgui:brand "Enkerli" ;\n'
        '        modgui:label "Vane" ;\n'
        '        modgui:color "purple" ;\n'
        '        modgui:knob "black" ;\n'
        f"{ports_ttl} ;\n"
        "    ] .\n"
        f"{END}\n"
    )


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    bundle = os.path.abspath(sys.argv[1])
    if not os.path.isdir(bundle):
        sys.exit(f"not a directory: {bundle}")

    # Validate BEFORE touching the bundle so a parse miss can never corrupt it.
    ttl = read_all_ttl(bundle)
    uri = find_uri(ttl)
    idx = symbol_indices(ttl)
    print(f"plugin URI: {uri}")

    # Safety: never write an empty modgui:port list (invalid Turtle that
    # corrupts manifest.ttl and makes MOD unable to instantiate the plugin).
    found = [s for s, _ in CONTROLS if s in idx]
    if not found:
        sample = sorted(idx)[:8]
        sys.exit("ERROR: none of the control symbols were found in the bundle "
                 "TTL — aborting WITHOUT modifying the bundle.\n"
                 f"  wanted: {[s for s, _ in CONTROLS]}\n"
                 f"  parsed {len(idx)} symbols, e.g.: {sample}\n"
                 "Send a maintainer the dsp.ttl port format so the parser/symbols "
                 "can be corrected.")

    src_modgui = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                              "..", "..", "modgui")
    dst_modgui = os.path.join(bundle, "modgui")
    shutil.rmtree(dst_modgui, ignore_errors=True)
    shutil.copytree(src_modgui, dst_modgui)
    print(f"copied modgui assets -> {dst_modgui}")

    manifest = os.path.join(bundle, "manifest.ttl")
    with open(manifest, encoding="utf-8") as f:
        body = f.read()
    # strip any previously injected block (idempotent re-runs)
    body = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n?",
                  "", body, flags=re.S)
    body = body.rstrip() + "\n" + build_block(uri, idx)
    with open(manifest, "w", encoding="utf-8") as f:
        f.write(body)
    print(f"patched {manifest}")
    print("Done. Install: sudo cp -r '%s' /var/modep/lv2/ && "
          "sudo systemctl restart modep-mod-ui modep-mod-host" % bundle)


if __name__ == "__main__":
    main()
