#!/usr/bin/env python3
"""Inject Vane's minimal modgui into a built Vane.lv2 bundle.

JUCE 8 exposes parameters as LV2 patch parameters (not control ports), and
MOD-UI binds those by URI via mod-parameter-uri (see modgui/icon.html). So this
script does NOT need port symbols at all — it:
  1. copies modgui/ assets into the bundle,
  2. substitutes the plugin URI into icon.html's __VANE_URI__ token,
  3. appends a (parameter-only) modgui:gui block to manifest.ttl.

JUCE regenerates the bundle (no modgui) on every build, so re-run afterwards;
it is idempotent.

Usage:
    python3 Tools/modgui/apply.py <path/to/Vane.lv2>

Then install:
    sudo cp -r <path/to/Vane.lv2> /var/modep/lv2/
    sudo systemctl restart modep-mod-ui modep-mod-host
"""
import os, re, shutil, sys

DEFAULT_URI = "https://enkerli.com/plugins/Vane"
BEGIN = "# >>> vane modgui (generated by Tools/modgui/apply.py)"
END   = "# <<< vane modgui"


def find_uri(bundle):
    """Plugin URI = subject declared 'a lv2:Plugin' across the bundle's TTL."""
    for fn in os.listdir(bundle):
        if not fn.endswith(".ttl"):
            continue
        with open(os.path.join(bundle, fn), encoding="utf-8") as f:
            m = re.search(r"<(https?://[^>]+)>\s*\n?\s*a\s+lv2:Plugin", f.read())
            if m:
                return m.group(1)
    return DEFAULT_URI


def modgui_block(uri):
    return (
        f"\n{BEGIN}\n"
        "@prefix modgui: <http://moddevices.com/ns/modgui#> .\n\n"
        f"<{uri}>\n"
        "    modgui:gui [\n"
        "        modgui:resourcesDirectory <modgui> ;\n"
        "        modgui:iconTemplate <modgui/icon.html> ;\n"
        "        modgui:stylesheet <modgui/style.css> ;\n"
        "        modgui:screenshot <modgui/screenshot.png> ;\n"
        "        modgui:thumbnail <modgui/thumbnail.png> ;\n"
        '        modgui:brand "Enkerli" ;\n'
        '        modgui:label "Vane" ;\n'
        '        modgui:color "purple" ;\n'
        "    ] .\n"
        f"{END}\n"
    )


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    bundle = os.path.abspath(sys.argv[1])
    if not os.path.isdir(bundle):
        sys.exit(f"not a directory: {bundle}")

    uri = find_uri(bundle)
    print(f"plugin URI: {uri}")

    # 1. copy assets
    src = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "modgui")
    dst = os.path.join(bundle, "modgui")
    shutil.rmtree(dst, ignore_errors=True)
    shutil.copytree(src, dst)
    print(f"copied modgui assets -> {dst}")

    # 2. substitute the plugin URI into the icon template
    icon = os.path.join(dst, "icon.html")
    with open(icon, encoding="utf-8") as f:
        html = f.read()
    n = html.count("__VANE_URI__")
    html = html.replace("__VANE_URI__", uri)
    with open(icon, "w", encoding="utf-8") as f:
        f.write(html)
    print(f"substituted plugin URI into icon.html ({n} sites)")

    # 3. append modgui:gui block (idempotent)
    manifest = os.path.join(bundle, "manifest.ttl")
    with open(manifest, encoding="utf-8") as f:
        body = f.read()
    body = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n?",
                  "", body, flags=re.S)
    body = body.rstrip() + "\n" + modgui_block(uri)
    with open(manifest, "w", encoding="utf-8") as f:
        f.write(body)
    print(f"patched {manifest}")
    print("Install: sudo cp -r '%s' /var/modep/lv2/ && "
          "sudo systemctl restart modep-mod-ui modep-mod-host" % bundle)


if __name__ == "__main__":
    main()
