#include "PluginEditor.h"
#include "BuildStamp.h"   // generated every build — always shows current time

VaneEditor::VaneEditor(VaneProcessor& p)
    : AudioProcessorEditor(p), vaneProcessor(p)
{
    setSize(480, 320);

    addAndMakeVisible(reconnectMtsButton);
    reconnectMtsButton.onClick = [this] {
        vaneProcessor.reconnectMTS();
    };

    // monoButton is a toggle button wired to "monoMode" via ButtonAttachment.
    // The label is kept up-to-date each timer tick to reflect the current state.
    addAndMakeVisible(monoButton);
    monoButton.setClickingTogglesState(true);

    startTimerHz(2);   // refresh MTS label + mono button twice per second
}

VaneEditor::~VaneEditor() { stopTimer(); }

void VaneEditor::timerCallback()
{
    bool connected = vaneProcessor.mtsConnected();
    reconnectMtsButton.setButtonText(connected ? "MTS-ESP: connected" : "MTS-ESP: reconnect");
    reconnectMtsButton.setColour(juce::TextButton::buttonColourId,
        connected ? juce::Colour(0xff1a3a1a) : juce::Colour(0xff3a1a1a));

    // Update mono button label and colour to reflect current toggle state.
    bool isMono = monoButton.getToggleState();
    monoButton.setButtonText(isMono ? "Mono" : "Poly");
    monoButton.setColour(juce::TextButton::buttonColourId,
        isMono ? juce::Colour(0xff1a2a3a) : juce::Colour(0xff252520));
}

void VaneEditor::paint(juce::Graphics& g)
{
    g.fillAll(juce::Colour(0xff111118));

    g.setColour(juce::Colour(0xffb0b8d0));
    g.setFont(juce::Font(juce::FontOptions{}.withHeight(22.0f)));
    g.drawText("Vane", getLocalBounds().removeFromTop(55),
               juce::Justification::centred);

    g.setFont(juce::Font(juce::FontOptions{}.withHeight(12.0f)));
    g.setColour(juce::Colour(0xff606878));
    g.drawText(juce::String::fromUTF8("MPE  \xc2\xb7  MTS-ESP  \xc2\xb7  CC modulation"),
               getLocalBounds().withTrimmedTop(56).removeFromTop(20),
               juce::Justification::centred);

    // Version + build stamp — VANE_BUILD_STAMP comes from BuildStamp.h,
    // regenerated by cmake/GenBuildStamp.cmake on every build.
    g.setFont(juce::Font(juce::FontOptions{}.withHeight(12.0f)));
    g.setColour(juce::Colour(0xffa8b4c8));
    g.drawText(juce::String("v") + JucePlugin_VersionString
                   + "  \xc2\xb7  " VANE_BUILD_STAMP,
               getLocalBounds().removeFromBottom(22),
               juce::Justification::centred);
}

void VaneEditor::resized()
{
    // MTS reconnect button: centred, slightly above centre
    reconnectMtsButton.setBounds(
        getLocalBounds().withSizeKeepingCentre(160, 26).translated(0, 20));

    // Mono/poly toggle: sits directly below the MTS button with a small gap
    monoButton.setBounds(
        getLocalBounds().withSizeKeepingCentre(80, 26).translated(0, 55));
}
