#include "PluginEditor.h"
#include "BuildStamp.h"   // generated every build — always shows current time

VaneEditor::VaneEditor(VaneProcessor& p)
    : AudioProcessorEditor(p), vaneProcessor(p)
{
    setSize(480, 320);

    addAndMakeVisible(reconnectMtsButton);
    reconnectMtsButton.onClick = [this] {
        vaneProcessor.reconnectMTS();
    };

    // ── Preset strip ─────────────────────────────────────────────────────────
    addAndMakeVisible(presetBox);
    presetBox.setTextWhenNothingSelected("-- init --");
    refreshPresetBox();

    // Selecting a preset from the combo box loads it immediately.
    presetBox.onChange = [this] {
        auto name = presetBox.getText();
        if (name.isNotEmpty() && name != "-- init --")
            vaneProcessor.presetManager.loadPreset(name);
    };

    addAndMakeVisible(savePresetButton);
    savePresetButton.onClick = [this] {
        // Show a modal text input so the player can name the preset.
        // AlertWindow is heap-allocated; deleteWhenDismissed=true cleans it up.
        auto* win = new juce::AlertWindow("Save Preset", "Name:",
                                          juce::MessageBoxIconType::NoIcon);
        win->addTextEditor("name",
                           vaneProcessor.presetManager.getCurrentPresetName(), {});
        win->addButton("Save",   1, juce::KeyPress(juce::KeyPress::returnKey));
        win->addButton("Cancel", 0, juce::KeyPress(juce::KeyPress::escapeKey));

        win->enterModalState(
            true,
            juce::ModalCallbackFunction::create([win, this](int result) {
                if (result == 1) {
                    auto name = win->getTextEditorContents("name").trim();
                    if (name.isNotEmpty()) {
                        vaneProcessor.presetManager.savePreset(name);
                        refreshPresetBox();
                    }
                }
            }),
            true /* deleteWhenDismissed */);
    };

    addAndMakeVisible(deletePresetButton);
    deletePresetButton.setTooltip("Delete selected preset");
    deletePresetButton.onClick = [this] {
        auto name = presetBox.getText();
        if (name.isEmpty() || name == "-- init --")
            return;

        auto options = juce::MessageBoxOptions()
            .withIconType(juce::MessageBoxIconType::WarningIcon)
            .withTitle("Delete Preset")
            .withMessage("Delete \"" + name + "\"?")
            .withButton("Delete")
            .withButton("Cancel");

        juce::AlertWindow::showAsync(options, [name, this](int result) {
            if (result == 1) {   // "Delete" is the first button → result 1
                vaneProcessor.presetManager.deletePreset(name);
                refreshPresetBox();
            }
        });
    };

    // monoButton is a toggle button wired to "monoMode" via ButtonAttachment.
    // The label is kept up-to-date each timer tick to reflect the current state.
    addAndMakeVisible(monoButton);
    monoButton.setClickingTogglesState(true);

    startTimerHz(2);   // refresh MTS label + mono button twice per second
}

VaneEditor::~VaneEditor() { stopTimer(); }

void VaneEditor::timerCallback()
{
    bool connected = vaneProcessor.mtsConnected();
    reconnectMtsButton.setButtonText(connected ? "MTS-ESP: connected" : "MTS-ESP: reconnect");
    reconnectMtsButton.setColour(juce::TextButton::buttonColourId,
        connected ? juce::Colour(0xff1a3a1a) : juce::Colour(0xff3a1a1a));

    // Update mono button label and colour to reflect current toggle state.
    bool isMono = monoButton.getToggleState();
    monoButton.setButtonText(isMono ? "Mono" : "Poly");
    monoButton.setColour(juce::TextButton::buttonColourId,
        isMono ? juce::Colour(0xff1a2a3a) : juce::Colour(0xff252520));
}

void VaneEditor::paint(juce::Graphics& g)
{
    g.fillAll(juce::Colour(0xff111118));

    g.setColour(juce::Colour(0xffb0b8d0));
    g.setFont(juce::Font(juce::FontOptions{}.withHeight(22.0f)));
    g.drawText("Vane", getLocalBounds().removeFromTop(55),
               juce::Justification::centred);

    g.setFont(juce::Font(juce::FontOptions{}.withHeight(12.0f)));
    g.setColour(juce::Colour(0xff606878));
    g.drawText(juce::String::fromUTF8("MPE  \xc2\xb7  MTS-ESP  \xc2\xb7  CC modulation"),
               getLocalBounds().withTrimmedTop(56).removeFromTop(20),
               juce::Justification::centred);

    // Version + build stamp — VANE_BUILD_STAMP comes from BuildStamp.h,
    // regenerated by cmake/GenBuildStamp.cmake on every build.
    g.setFont(juce::Font(juce::FontOptions{}.withHeight(12.0f)));
    g.setColour(juce::Colour(0xffa8b4c8));
    g.drawText(juce::String("v") + JucePlugin_VersionString
                   + juce::String::fromUTF8("  \xc2\xb7  " VANE_BUILD_STAMP),
               getLocalBounds().removeFromBottom(22),
               juce::Justification::centred);
}

void VaneEditor::resized()
{
    // ── Preset strip: full width below the subtitle ───────────────────────────
    // Layout (480 wide, left/right margin 20 px each):
    //   ComboBox | 8px gap | Save (60px) | 4px gap | Delete (26px) | margin
    constexpr int margin = 20;
    constexpr int stripY = 85;
    constexpr int stripH = 26;
    constexpr int saveW  = 60;
    constexpr int delW   = 26;
    constexpr int gap    = 6;
    int availW = getWidth() - 2 * margin - saveW - delW - 2 * gap;

    presetBox.setBounds         (margin,                             stripY, availW, stripH);
    savePresetButton.setBounds  (margin + availW + gap,              stripY, saveW,  stripH);
    deletePresetButton.setBounds(margin + availW + gap + saveW + gap, stripY, delW,   stripH);

    // MTS reconnect button: centred, slightly above centre
    reconnectMtsButton.setBounds(
        getLocalBounds().withSizeKeepingCentre(160, 26).translated(0, 20));

    // Mono/poly toggle: sits directly below the MTS button with a small gap
    monoButton.setBounds(
        getLocalBounds().withSizeKeepingCentre(80, 26).translated(0, 55));
}

void VaneEditor::refreshPresetBox()
{
    auto names   = vaneProcessor.presetManager.getPresetNames();
    auto current = vaneProcessor.presetManager.getCurrentPresetName();

    presetBox.clear(juce::dontSendNotification);

    // ID 1 is the "nothing saved/selected" sentinel; preset names start at ID 2.
    presetBox.addItem("-- init --", 1);
    for (int i = 0; i < names.size(); ++i)
        presetBox.addItem(names[i], i + 2);

    if (current.isEmpty())
        presetBox.setSelectedId(1, juce::dontSendNotification);
    else
        presetBox.setText(current, juce::dontSendNotification);
}
